# Generated by Django 4.2.4 on 2023-11-01 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_comments'),
        ('accounts', '0004_remove_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='products.shops', verbose_name='فروشگاه'),
        ),
    ]
