# Generated by Django 4.2.4 on 2023-11-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_shop_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='فروشگاه'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
