# Generated by Django 4.2.4 on 2023-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_shop_user_is_seller_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='فروشنده'),
        ),
    ]
