# Generated by Django 4.2.4 on 2023-12-07 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_near_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'پذیرفته شده'), ('i', 'در حال بررسی'), ('r', 'رد شده')], default='i', max_length=1, verbose_name='وضعیت تیکت')),
                ('admin_text_message', models.TextField(blank=True, null=True, verbose_name='متن مدیر سایت')),
                ('user_text_message', models.TextField(blank=True, null=True, verbose_name='متن کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست داده شده')),
                ('responced_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='ادمین پاسخگو')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ('created_at',),
            },
        ),
    ]
