# Generated by Django 4.2.4 on 2023-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.SmallIntegerField(verbose_name='قیمت محصول'),
        ),
    ]
