# Generated by Django 4.2.4 on 2023-10-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cities_options_remove_shops_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shops', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='rank_shop',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('o', 'Out of range')], default='o', max_length=1, verbose_name='جایگاه فروشگاه'),
        ),
    ]
