# Generated by Django 4.2.4 on 2023-11-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_shops_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
