# Generated by Django 4.2.4 on 2023-11-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_shops_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام فروشگاه'),
        ),
    ]
