# Generated by Django 4.2.4 on 2023-11-24 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_alter_products_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='buyer',
            field=models.ManyToManyField(through='products.ProductsSeller', to=settings.AUTH_USER_MODEL),
        ),
    ]
