# Generated by Django 4.2.4 on 2023-11-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_productsseller_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='buyer',
        ),
    ]
