# Generated by Django 4.2.4 on 2024-01-17 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0028_alter_shops_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsseller',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_products', to='products.products', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='productsseller',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='خریدار'),
        ),
    ]
