# Generated by Django 4.2.4 on 2023-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='فروشنده'),
        ),
    ]
