# Generated by Django 4.2.4 on 2023-11-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_near_seller',
            field=models.BooleanField(default=False, verbose_name='آماده برای فروشندگی'),
        ),
    ]
