# Generated by Django 4.2.4 on 2023-12-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='responced_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='ادمین پاسخگو'),
        ),
    ]
