# Generated by Django 4.2.4 on 2023-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shops_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='position',
            field=models.IntegerField(default=0, verbose_name='جایگاه فروشگاه'),
        ),
    ]
