# Generated by Django 4.2.4 on 2023-10-07 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_shops_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='city',
        ),
        migrations.AlterField(
            model_name='shops',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AddField(
            model_name='shops',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='products.cities', verbose_name='شهر'),
        ),
    ]
