# Generated by Django 4.2.4 on 2023-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_shops_city_alter_shops_seller_shops_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='city',
        ),
        migrations.AddField(
            model_name='shops',
            name='city',
            field=models.ManyToManyField(null=True, related_name='shops', to='products.cities', verbose_name='شهر'),
        ),
    ]
