# Generated by Django 4.2.4 on 2023-10-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_shops_city_shops_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ('created_at',), 'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.RemoveField(
            model_name='shops',
            name='position',
        ),
        migrations.AddField(
            model_name='shops',
            name='rank_shop',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', ''), ('f', 'F'), ('o', 'Out of range')], default='o', max_length=1, verbose_name='جایگاه فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='city',
            field=models.ManyToManyField(related_name='shops', to='products.cities', verbose_name='شهر'),
        ),
    ]
