# Generated by Django 4.2.4 on 2023-10-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_shop_alter_shops_rank_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ('position',), 'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.RemoveField(
            model_name='shops',
            name='seller',
        ),
    ]
