# Generated by Django 4.2.4 on 2023-11-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cities_options_remove_shops_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
