# Generated by Django 4.2.4 on 2023-11-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_comments_options_productsseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsseller',
            name='count',
            field=models.IntegerField(verbose_name='تعداد کالا'),
        ),
    ]
