# Generated by Django 4.2.4 on 2023-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productsseller_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='productsseller',
            name='status',
            field=models.CharField(choices=[('b', 'درحال خرید'), ('s', 'خریداری شده')], default='b', max_length=1, verbose_name='وضعیت سفارش'),
        ),
    ]
