# Generated by Django 4.2.4 on 2023-11-14 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_alter_products_slug_alter_productsseller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='seller',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
    ]
