# Generated by Django 4.2.4 on 2023-11-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_categories_name_alter_cities_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.shops', verbose_name='فروشگاه'),
        ),
    ]
