# Generated by Django 4.2.4 on 2023-11-26 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_products_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsseller',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_products', to='products.products', verbose_name='کالا'),
        ),
    ]
