# Generated by Django 4.2.4 on 2023-12-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
